### ISSUE TITLE
Failed to load vslsmashsource.dll.

### ISSUE THREAD

**Issue by theChaosCoder** [MaverickTse/LSW-AutoCIBuild#2]
I tried this dll https://github.com/MaverickTse/LSW-AutoCIBuild/releases/tag/1.0.2

`Failed to load vslsmashsource.dll. GetLastError() returned 193. `

I'm using VapourSynth 64bit. Is this a 32bit dll? If so could your auto-bot also compile a 64bit version?

**Comment by MaverickTse** [comment]
Building both bit-ness on Travis would exceed time-limit. Therefore this is 32bit only and can't extend to 64bit. 
You (or someone else) can fork and modify a little to get the 64-bit only build however.

**Comment by theChaosCoder** [comment]
ok thx. A small hint what it's only 32bit would be still nice :) Since 99% of VS users use the 64bit version.

**Comment by MaverickTse** [comment]
I thought the vaporsynth official site hosted the L-SMASH link also... no more?
Actually I create this repo just for getting AviUtl plugin, therefore 32bit.

**Comment by theChaosCoder** [comment]
I'm not aware of any "official binaries" for VS. The last binary that I found on doom9 forums was from 2017.
